# coding:utf-8
import numpy as np
arr=np.array([[0,1,2],
                [3,4,5],
                [6,7,8]])
print(arr)
result=np.split(arr,3,axis=1)
print(result[0])
print(result[1])
print('利用np.hsplit水平分割数组')
result2=np.hsplit(arr,3)
print(arr)
print(result2[0])
print(result2[1])
print(result2[2])
print('利用np.vsplit垂直分割数组')
result4=np.vsplit(arr,3)
print(arr)
print(result4[0])
print(result4[1])
print(result4[2])
print('按深度方向分割数组')
arr1=np.arange(8).reshape(2,2,2)
print(arr1)
result5=np.dsplit(arr1,2)
print(result5[0])
print(result5[1])

m = np.arange(9).reshape(3,3)
print('m')
print(m)
#2*m
doubleM = 2*m
print('doubleM')
print(doubleM)
#组合m与doubleM
result1 = np.hstack((m,doubleM))
print(result1)
result2 = np.concatenate((m,doubleM),axis = 1)
print(result2)
print('深度组合m与doubleM')
result5=np.dstack((m,doubleM))
print(result5)
print('列组合m与doubleM')
result6=np.column_stack((m,doubleM))
print(result6)
print('行组合m与doubleM')
result7 = np.row_stack((m,doubleM))
print(result7)